#- id: '2018090801'
########################################################
## Set Zwave config parameter for Multi04
########################################################
#  service: zwave.set_config_parameter
#  data_template: {
#                "node_id": 19,
#                "parameter": 7,
#                "value": 2
#                 }

- id: '2018082601'
########################################################
## Turn switch Inovelli01 SW2 (MAsterBedroom) "ON" if it was "OFF" triggered by
## Multisensor4 After that take 4 snapshoots and send
## them by mail "notify.MailtoPykodel"
########################################################
  alias: Turn on Inolelli01 SW2  when there is movement
  trigger:
    - entity_id: binary_sensor.multi04_motion
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '19:00:00'
      before: '22:50:00'
      #weekday:
      #- mon  
      #- tue
      #- wed
      #- thu
      #- fri     
    - condition: state
      entity_id: switch.inovelli_2ch_01_2
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.inovelli_2ch_01_2

- id: '2018082602'
########################################################
## Turn switch Inovelli01 SW2 "OFF" if it was "ON" triggered by
## Multisensor4 after 15 minutes "NO MOTION"
##
########################################################
  alias: Turn off Inovelli01 SW2 15 minutes after last movement
  trigger:
  - entity_id: binary_sensor.multi04_motion
    for:
      minutes: 15
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.inovelli_2ch_01_2
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.inovelli_2ch_01_2




- id: '20180083001' 
########################################################
## Turn switch Neo1 "ON" if it was "OFF" triggered by 
## Multisensor1 After that take 4 snapshoots and send
## them by mail "notify.MailtoPykodel" 
########################################################
  alias: Turn on Neo1 when there is movement
  trigger:
    - entity_id: binary_sensor.multi01_motion
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.neo_coolcam_power_plug_12a_switch01
      state: 'off'
  action:
    - service: homeassistant.turn_on 
      entity_id: switch.neo_coolcam_power_plug_12a_switch01
    - service: camera.snapshot
      data:
        entity_id: camera.camera4
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_01.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_01.jpg"
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_01cor.jpg"
    - delay: '00:00:02'
    - service: camera.snapshot
      data:
        entity_id: camera.camera4
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_02.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_02.jpg"
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_02cor.jpg"
    - delay: '00:00:12'
    - service: camera.snapshot
      data:
        entity_id: camera.camera4
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_03.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_03.jpg"
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_03cor.jpg"
    - delay: '00:00:25'
    - service: camera.snapshot
      data:
        entity_id: camera.camera4
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_04.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_04.jpg"
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera4_04cor.jpg"
    - service: notify.MailtoPykodel
      data_template:
        title: "Basement Motion Detected"
        message: "Motion Detected in Basement by Multisensor Multi01"
        data:
          images:
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera4_01cor.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera4_02cor.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera4_03cor.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera4_04cor.jpg
          html: >
            <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
            <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
              <head>

                <meta charset="UTF-8">
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Switch1 Triggered</title>
                <style type="text/css">
                  h1,h2,h3,h4,h5,h6 {
                  font-family:Arial,sans-serif;
                  }
                </style>
              </head>
              <body>
                <h1>Motion in Basement  0sec</h1>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera4?api_password=3health1">
                <img style="width: 100%; alt="Image1 from Camera4" src="cid:snapshot_camera4_01cor.jpg" /></a>
                <h4>4 sec</h4>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera4?api_password=3health1">
                <img style="width: 100%; alt="Image2 from Camera4" src="cid:snapshot_camera4_02cor.jpg" /></a>
                <h4>16 sec</h4>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera4?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera4" src="cid:snapshot_camera4_03cor.jpg" /></a>
                <h4>32 sec</h4>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera4?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera4" src="cid:snapshot_camera4_04cor.jpg" /></a>
              </body>
            </html>
#
#
- id: '2018083002'
########################################################
## Turn switch Neo1 "OFF" if it was "ON" triggered by
## Multisensor1 after 15 minutes "NO MOTION"
##
########################################################
  alias: Turn off Neo1 15 minutes after last movement
  trigger:
  - entity_id: binary_sensor.multi01_motion
    for:
      minutes: 15
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.neo_coolcam_power_plug_12a_switch01
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.neo_coolcam_power_plug_12a_switch01
#
#
#
- id: '2018073002' 
########################################################
## Turn switch Neo3 "OFF" if it was "ON" triggered by 
## Multisensor1 after 15 minutes "NO MOTION"
##  
########################################################
  alias: Turn off Neo3 3 minutes after last movement
  trigger:
  - entity_id: binary_sensor.multisensor2_motion
    for:
      minutes: 15
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.neo_coolcam_power_plug_12a_switch_33
    state: 'on'
  action:
  - service: homeassistant.turn_off 
    entity_id: switch.neo_coolcam_power_plug_12a_switch_33
#
#
#
- id: '2018073003'
########################################################
## Turn switch Neo3 "OFF" if it was "ON" triggered by 
## switch Neo2 from "OFF" to "ON". After that take 4 
## snapshoots and send them by mail "notify.MailtoPykodel" 
########################################################
  alias: Turn off Neo3 if Neo2 on
  trigger:
    - entity_id: switch.neo_coolcam_power_plug_12a_switch_22
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.neo_coolcam_power_plug_12a_switch_33
      state: 'on'
  action:
    - service: homeassistant.turn_off 
      entity_id: switch.neo_coolcam_power_plug_12a_switch_33
    - service: camera.snapshot
      data:
        entity_id: camera.camera1
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera1_11.jpg"
    - service: camera.snapshot
      data:
        entity_id: camera.camera2
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_11.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_11.jpg"  
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_11c.jpg"  
    - delay: '00:00:02'
    - service: camera.snapshot
      data:
        entity_id: camera.camera1
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera1_12.jpg"
    - service: camera.snapshot
      data:
        entity_id: camera.camera2
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_12.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_12.jpg"  
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_12c.jpg"  
    - delay: '00:00:12'
    - service: camera.snapshot
      data:
        entity_id: camera.camera1
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera1_13.jpg"
    - service: camera.snapshot
      data:
        entity_id: camera.camera2
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_13.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_13.jpg"  
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_13c.jpg"  
    - delay: '00:00:25'
    - service: camera.snapshot
      data:
        entity_id: camera.camera1
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera1_14.jpg"
    - service: camera.snapshot
      data:
        entity_id: camera.camera2
        filename: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_14.jpg"
    - service: shell_command.fix_snapshot
      data:
        filename1: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_14.jpg"  
        filename2: "/home/homeassistant/.homeassistant/downloads/snapshot_camera2_14c.jpg"  
    - service: notify.MailtoPykodel
      data_template:
        title: "Sw3 triggered"
        message: "Switch3 Trigger Snapshot"
        data:
          images:
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera1_11.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera1_12.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera1_13.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera1_14.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera2_11c.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera2_12c.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera2_13c.jpg
            - /home/homeassistant/.homeassistant/downloads/snapshot_camera2_14c.jpg
          
          html: >
            <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
            <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
              <head>
                <meta charset="UTF-8">
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Switch Triggered</title>
                <style type="text/css">
                  h1,h2,h3,h4,h5,h6 {
                  font-family:Arial,sans-serif;
                  }
                </style>
              </head>
              <body>
                <h1>Switch3 Triggered 0sec</h1>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera1?api_password=3health1">
                <img style="width: 100%; alt="Image1 from Camera1" src="cid:snapshot_camera1_11.jpg" /></a>
                <h6>4 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera1?api_password=3health1">
                <img style="width: 100%; alt="Image2 from Camera1" src="cid:snapshot_camera1_12.jpg" /></a>
                <h6>16 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera1?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera1" src="cid:snapshot_camera1_13.jpg" /></a>
                <h6>32 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera1?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera1" src="cid:snapshot_camera1_14.jpg" /></a>
                <h1>Switch3 Triggered (camera2) 0sec</h1>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera2?api_password=3health1">
                <img style="width: 100%; alt="Image1 from Camera2" src="cid:snapshot_camera2_11c.jpg" /></a>
                <h6>4 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera2?api_password=3health1">
                <img style="width: 100%; alt="Image2 from Camera2" src="cid:snapshot_camera2_12c.jpg" /></a>
                <h6>16 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera2?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera2" src="cid:snapshot_camera2_13c.jpg" /></a>
                <h6>32 sec</h6>
                <a href="https://jumpier-panther-8852.dataplicity.io/api/camera_proxy_stream/camera.camera2?api_password=3health1">
                <img style="width: 100%; alt="Image3 from Camera2" src="cid:snapshot_camera2_14c.jpg" /></a>
              </body>
            </html>
#
#
#
- id: '2018073004'
########################################################
## Turn Water Valve "OFF" if it was "ON" triggered by 
## Water Leak sensor from "OFF" to "ON". After that send
## an mail "notify.MailtoPykodel" 
########################################################
  alias: Auto_Switch_Water
  trigger:
  - entity_id: binary_sensor.neo_coolcam_water_leakage_detector_sensor
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.sigma_valveswitch
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.sigma_valveswitch
  - service: notify.MailtoPykodel
    data:
      title: "FLOOD ALERT"
      message: "WaterSwitch trigerred by WaterLeak sensor"
