########################
# USB_Camera
########################
- platform: mjpeg 
  mjpeg_url: http://localhost:8081 
  name: Camera1
  username: viewer
  password: 1234
########################
# Network_Camera Indoor 
########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.221/img/video.mjpeg
  name: Camera2
  username: viewer
  password: 1234
###########################
# Network_Camera External 
###########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.222/img/video.mjpeg
  name: Camera3
  username: viewer 
  password: 1234
###########################
# Network_Camera D-Link01 
###########################
- platform: mjpeg 
  mjpeg_url: http://viewer:1234@192.168.0.223/video1.mjpg
  name: Camera4
###########################
# Network_Camera Digoo
###########################
#- platform: ffmpeg
#  name: Camera4
#  input: rtsp://admin:vw1234wv@192.168.0.17/onvif2
#  extra_arguments: -q:v 2

