########################
# USB_Camera
########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.218:8081
  name: Camera1
  username: viewer
  password: 1234
########################
# Network_Camera Indoor 
########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.221/img/video.mjpeg
  name: Camera2
  username: viewer
  password: 1234
###########################
# Network_Camera External 
###########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.222/img/video.mjpeg
  name: Camera3
  username: viewer 
  password: 1234
########################
# USB_Camera2
########################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.218:8082
  name: Camera4
  username: viewer
  password: 1234
###########################
# Network_Camera D-Link01 
###########################
- platform: mjpeg 
  mjpeg_url: http://viewer:1234@192.168.0.223/video1.mjpg
  name: Camera5
###########################
# Network_Camera D-Link02
###########################
- platform: mjpeg 
  mjpeg_url: http://viewer:1234@192.168.0.224:8080/video1.mjpg
  name: Camera6
###########################
# Network_Camera D-Link03
###########################
- platform: mjpeg 
  mjpeg_url: http://viewer:1234@192.168.0.225/video/mjpg.cgi
  name: Camera7
#- platform: ffmpeg
#  name: Camera6
#  input: rtsp://192.168.0.224/live1.sdp
#  extra_arguments: -q:v 2

####################################
## Network_Camera External  OC821D 
#####################################
- platform: mjpeg 
  mjpeg_url: http://192.168.0.226/img/video.mjpeg
  name: Camera8
  username: viewer 
  password: 1234



