### Groups ###
# Views
default_view:
  view: yes
  name: AllRooms
  entities:
    - sensor.disk_use_percent
    - sensor.last_boot
    - sensor.processor_use
    - sensor.2gig_technologies_ct101_thermostat_iris_temperature  
    - sensor.2gig_technologies_ct101_thermostat_iris_relative_humidity  
   #- sensor.weather_temperature
   #- sensor.weather_humidity
    - binary_sensor.hvacfan  
    - binary_sensor.neo_coolcam_water_leakage_detector_sensor01
    - binary_sensor.neo_coolcam_water_leakage_detector_sensor02
    - binary_sensor.neo_coolcam_water_leakage_detector_sensor03
    - sensor.aeotec_zw095_home_energy_meter_gen5_power
    - sensor.aeotec_zw095_home_energy_meter_gen5_energy
    - binary_sensor.ecolink_garage_door_tilt_sensor_sensor
    - binary_sensor.kaipule_im20_doorwindow_sensor_sensor   
    - binary_sensor.kaipule_im20_doorwindow_sensor_sensor_2   
    - binary_sensor.kaipule_im20_doorwindow_sensor_sensor_3   
    - group.basement
    - group.kitchen
    - group.chatroom
    - group.bedroom1
    - group.office
   #- group.modem
    - group.masteroom
    - group.attic
    - group.date_time

date_time:
  name: Date and Time
  control: hidden
  entities:
    - sensor.time
    - sensor.date
    - sensor.time_utc
    - sensor.time_in_odessa
    - script.test_notification    

basement:
  name: Basement
  control: hidden
  entities:
    - binary_sensor.multi01_motion
    - binary_sensor.multi01_tamper
      ## Multi01
    - sensor.vision_zp3111_multisensor_4in1_luminance_1
    - sensor.vision_zp3111_multisensor_4in1_relative_humidity_1
    - sensor.vision_zp3111_multisensor_4in1_temperature_1
      #- sensor.vision_zp3111_multisensor_4in1_battery_1
      ## Zen21
    - switch.zooz_zen21_switch_v20_switch_01
      ## Neo01
    - sensor.neo_coolcam_power_plug_12a_power01 
    - sensor.neo_coolcam_power_plug_12a_energy01
    - switch.neo_coolcam_power_plug_12a_switch01

kitchen:
  name: MainFloor 
  control: hidden
  entities:
    - binary_sensor.ezm01_motion
    - sensor.homeseer_hsm200_wireless_multisensor_luminance_1
    - sensor.homeseer_hsm200_wireless_multisensor_temperature_1      
      ## Neo02
    - sensor.neo_coolcam_power_plug_12a_power02 
    - switch.neo_coolcam_power_plug_12a_switch02
    #- sensor.neo_coolcam_power_plug_12a_voltage02
    #- sensor.neo_coolcam_power_plug_12a_current02
      ##
    - binary_sensor.multi05_motion
    - binary_sensor.multi05_tamper
      ## Multi05
    - sensor.vision_zp3111_multisensor_4in1_luminance_5
    - sensor.vision_zp3111_multisensor_4in1_relative_humidity_5
    - sensor.vision_zp3111_multisensor_4in1_temperature_5
      ## Zooz01 
    - sensor.hank_hkzwso03_smart_plug_power01  
    - switch.hank_hkzwso03_smart_plug_switch01  
    #- sensor.hank_hkzwso03_smart_plug_voltage01  
    #- sensor.hank_hkzwso03_smart_plug_current01  

chatroom:
  name: ChatRoom 
  control: hidden
  entities:
      ## Neo04
    - sensor.neo_coolcam_power_plug_12a_power04
    - switch.neo_coolcam_power_plug_12a_switch04
    #- sensor.neo_coolcam_power_plug_12a_voltage04
    #- sensor.neo_coolcam_power_plug_12a_current04
      ## Dome01
    - sensor.dome_on_off_plug_in_switch01_power
    - switch.dome_on_off_plug_in_switch01_switch
      ## Dimmer Zen22 Chat Room (Node ID:42)
    - light.zooz_zen22_dimmer_v2_3_level
  

bedroom1:
  name: Vlad's Room
  control: hidden
  entities:
    - binary_sensor.multi03_motion
    - binary_sensor.multi03_tamper
      ## Multi03
    - sensor.vision_zp3111_multisensor_4in1_luminance_3
    - sensor.vision_zp3111_multisensor_4in1_relative_humidity_3
    - sensor.vision_zp3111_multisensor_4in1_temperature_3
      #- sensor.vision_zp3111_multisensor_4in1_battery_3
      ## Dimmer Zen22 (Node ID:32)
    - light.zooz_zen22_dimmer_v2_2_level
      ## Neo03
    - sensor.neo_coolcam_power_plug_12a_power03 
    - switch.neo_coolcam_power_plug_12a_switch03
    #- sensor.neo_coolcam_power_plug_12a_voltage03
    #- sensor.neo_coolcam_power_plug_12a_current03

office:
  name: Office
  control: hidden
  entities:
      ## HA02-white
    - switch.intermatic_ha02_appliance_module_switch 
      ## Neo06
    - sensor.neo_coolcam_power_plug_12a_power06 
    - switch.neo_coolcam_power_plug_12a_switch06
      ## Neo07
    - sensor.neo_coolcam_power_plug_12a_power07 
    - sensor.neo_coolcam_power_plug_12a_energy07
    - sensor.neo_coolcam_power_plug_12a_voltage07
    - sensor.neo_coolcam_power_plug_12a_current07
      
modem:
  name: Modem
  control: hidden
  entities:
      ## Neo05
      #- sensor.neo_coolcam_power_plug_12a_energy05
      #- sensor.neo_coolcam_power_plug_12a_power05 
    - switch.neo_coolcam_power_plug_12a_switch05

masteroom:
  name: Master Bedroom
  control: hidden
  entities:
    - binary_sensor.multi04_motion
    - binary_sensor.multi04_tamper
      ## Multi04
    - sensor.vision_zp3111_multisensor_4in1_luminance_4
    - sensor.vision_zp3111_multisensor_4in1_relative_humidity_4
    - sensor.vision_zp3111_multisensor_4in1_temperature_4
      #- sensor.vision_zp3111_multisensor_4in1_battery_4
      ## Dimmer Zen22 (Node ID:29)
    - light.zooz_zen22_dimmer_v2_1_level
      ## Inovelli01
    - switch.inovelli_2ch_01_1
    - switch.inovelli_2ch_01_2  

attic:
  name: AtticSpace
  control: hidden
  entities:
    - binary_sensor.multi02_motion
    - binary_sensor.multi02_tamper
      ## Multi02
    - sensor.vision_zp3111_multisensor_4in1_luminance_2
    - sensor.vision_zp3111_multisensor_4in1_relative_humidity_2
    - sensor.vision_zp3111_multisensor_4in1_temperature_2
      #- sensor.vision_zp3111_multisensor_4in1_battery_2

###############################################################
#
#  NewTab "THERMOSTAT" 
#
###############################################################    
thermostat_views:
  view: yes
  name: Climate
  entities:
  - group.thermostat_mode
  - group.temp
  - group.humid

thermostat_mode:
  name: Thermostat Id:28 
  control: hidden
  entities:
  - climate.2gig_technologies_ct101_thermostat_iris_cooling_1
  - climate.2gig_technologies_ct101_thermostat_iris_heating_1
  - sensor.thermostat_battery
    #- sensor.thermostat_cool_fan_state
    #- sensor.thermostat_heat_fan_state
  - sensor.thermostat_operation_mode_state
    #- sensor.thermostat_cool_operation_mode_state
    #- sensor.thermostat_heat_operation_mode_state
  - sensor.thermostat_current_temperature
  - sensor.2gig_technologies_ct101_thermostat_iris_relative_humidity
    #- sensor.thermostat_cool_current_temperature
    #- sensor.thermostat_heat_current_temperature
    #- sensor.thermostat_cool_temperature
    #- sensor.thermostat_heat_temperature
    #- sensor.thermostat_cool_min_temp
    #- sensor.thermostat_heat_min_temp
    #- sensor.thermostat_cool_max_temp
    #- sensor.thermostat_heat_max_temp
    #
    #
      ## Neo08
  - sensor.neo_coolcam_power_plug_12a_power08 
  - sensor.neo_coolcam_power_plug_12a_energy08
  - switch.neo_coolcam_power_plug_12a_switch08
    #- sensor.neo_coolcam_power_plug_12a_voltage08
    #- sensor.neo_coolcam_power_plug_12a_current08
    #
    #
      ##  Aeotec ZW078 heavy_duty Furnace Switch ID:39
  - sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_power
  - sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_energy
    #- sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_voltage
    #- sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_current
    #- sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_temperature
  - switch.aeotec_zw078_heavy_duty_smart_switch_gen5_switch

temp:
  name: Temperature
  control: hidden
  entities:
  - sensor.weather_temperature
  - sensor.vision_zp3111_multisensor_4in1_temperature_2        
  - sensor.garage_t1_temperature
  - sensor.basement_p1_temperature
  - sensor.vision_zp3111_multisensor_4in1_temperature_1        
  - sensor.vision_zp3111_multisensor_4in1_temperature_3        
  - sensor.vision_zp3111_multisensor_4in1_temperature_4
  - sensor.vision_zp3111_multisensor_4in1_temperature_5
  - sensor.thermostat_current_temperature
  - sensor.chatroom_p2_temperature
  - sensor.kitchen_p3_temperature
  - sensor.bathroom_t2_temperature
  - sensor.office_t3_temperature
  - sensor.homeseer_hsm200_wireless_multisensor_temperature_1       

humid:
  name: Humidity
  control: hidden
  entities:
  - sensor.weather_humidity
  - sensor.vision_zp3111_multisensor_4in1_relative_humidity_2
  - sensor.garage_t1_humidity
  - sensor.basement_p1_humidity
  - sensor.vision_zp3111_multisensor_4in1_relative_humidity_1
  - sensor.vision_zp3111_multisensor_4in1_relative_humidity_3
  - sensor.vision_zp3111_multisensor_4in1_relative_humidity_4
  - sensor.vision_zp3111_multisensor_4in1_relative_humidity_5
  - sensor.2gig_technologies_ct101_thermostat_iris_relative_humidity
  - sensor.chatroom_p2_humidity
  - sensor.kitchen_p3_humidity
  - sensor.bathroom_t2_humidity
  - sensor.office_t3_humidity

###############################################################
#
#  NewTab "HOME ENERGY MONITOR" HEM ID:25 
#
###############################################################
energy:
  view: yes
  name: Energy/Battery
  entities:
    - group.powermeter
    - group.hemvoltage
    - group.hempower
    - group.batteries
    - group.energydata
    - group.ups
   #- group.hemenergy
          
ups:
  name: BasementUPS
  control: hidden
  entities:
    - sensor.ups_battery_temperature
    - sensor.ups_input_volts
    - sensor.ups_battery_capacity
    - sensor.ups_battery_runtime_remain

batteries:
  name: Batteries
  control: hidden
  entities:
    - sensor.multi01_battery
    - sensor.multi02_battery
    - sensor.multi03_battery
    - sensor.multi04_battery
    - sensor.waterleaksensor01_battery
    - sensor.waterleaksensor02_battery
    - sensor.waterleaksensor03_battery
    - sensor.door01_battery
    - sensor.door02_battery
    - sensor.door03_battery
    - sensor.garagedoor_battery
    - sensor.basement_p1_battery
    - sensor.bathroom_t2_battery
    - sensor.chatroom_p2_battery
    - sensor.garage_t1_battery
    - sensor.kitchen_p3_battery
    - sensor.office_t3_battery  

powermeter:
  name: HomeEnergyMeter
  control: hidden
  entities:
    - sensor.aeotec_zw095_home_energy_meter_gen5_current
    - sensor.aeotec_zw095_home_energy_meter_gen5_voltage
    - sensor.aeotec_zw095_home_energy_meter_gen5_power
    - sensor.aeotec_zw095_home_energy_meter_gen5_energy
  
hemvoltage:
  name: Home Voltage,V
  control: hidden
  entities:
    - history_graph.hemvoltage_graph
        #- type: history-graph
        #title: 'HEMPower Graph'
        #entities:
        #- sensor.aeotec_zw095_home_energy_meter_gen5_power
        #hours_to_show: 150
hempower:
  name: Home Power,W
  control: hidden
  entities:
    - history_graph.hempower_graph
#hemenergy:
#  name: Home Energy,kWh
#  entities:
#    - history_graph.hemenergy_graph
      

energydata:
  name: Energy Usage
  control: hidden
  entities:
    - sensor.aeotec_zw095_home_energy_meter_gen5_energy
      #- sensor.hank_hkzwso03_smart_plug_power01  
    - sensor.hank_hkzwso03_smart_plug_energy01
      #- sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_power
    - sensor.aeotec_zw078_heavy_duty_smart_switch_gen5_energy
      #- sensor.neo_coolcam_power_plug_12a_power01 
    - sensor.neo_coolcam_power_plug_12a_energy01
      #- sensor.neo_coolcam_power_plug_12a_power02 
    - sensor.neo_coolcam_power_plug_12a_energy02
      #- sensor.neo_coolcam_power_plug_12a_power03 
    - sensor.neo_coolcam_power_plug_12a_energy03
      #- sensor.neo_coolcam_power_plug_12a_power04 
    - sensor.neo_coolcam_power_plug_12a_energy04
      #- sensor.neo_coolcam_power_plug_12a_power05 
    - sensor.neo_coolcam_power_plug_12a_energy05
      #- sensor.neo_coolcam_power_plug_12a_power06 
    - sensor.neo_coolcam_power_plug_12a_energy06
      #- sensor.neo_coolcam_power_plug_12a_power07 
    - sensor.neo_coolcam_power_plug_12a_energy07
      #- sensor.neo_coolcam_power_plug_12a_power08 
    - sensor.neo_coolcam_power_plug_12a_energy08
      #- sensor.dome_on_off_plug_in_switch01_power
    - sensor.dome_on_off_plug_in_switch01_energy
      #- sensor.dome_on_off_plug_in_switch02_power
    - sensor.dome_on_off_plug_in_switch02_energy


###############################################################
#
#  NewTab "Power Graphs" 
#
###############################################################
powergraphs:
  view: yes
  name: PowerStat 
  entities:
    - group.powerzooz
    - group.powerdome
    - group.powerneo
    - group.powerfurnace
      #- group.voltage


powerneo:
    name: PowerNeo
    entities:
    - history_graph.neopower_graphs
powerzooz:
    name: PowerZooz
    entities:
    - history_graph.zoozpower_graphs
powerdome:
    name: PowerDome
    entities:
    - history_graph.domepower_graphs
powerfurnace:
    name: PowerFurnace
    entities:
    - history_graph.furnacepower_graph
#voltage:
   #name: Voltage
   #entities:
   #- history_graph.voltage_graphs
      
###############################################################
#
#  NewTab "Water Control" 
#
###############################################################
watercontrol:
  view: yes
  name: Water 
  entities:
    - group.watervalve

watervalve:
  name: Water Leaks Control
  control: hidden
  entities:
    - sensor.waterleakstatus01
    - sensor.waterleakstatus02
    - sensor.waterleakstatus03
    - switch.sigma_valveswitch01    

###############################################################
#
#  NewTab "SECURITY" 
#
###############################################################
security:
  view: yes
  name: Security
  entities:
    - group.cameras

cameras:
  name: SecurityCameras
  control: hidden
  entities:
    - camera.camera1 
    - camera.camera2 
    - camera.camera3
    - camera.camera4
    - camera.camera5
    - camera.camera6
    - camera.camera7

###############################################################
#
#  NewTab "SWITCHES" 
#
###############################################################
power_switch:
  view: yes
  name: Switches
  control: hidden
  entities:
    #- group.all_switches
    - group.zoozswitch
    - group.inovelliswitch
    - group.neoswitch
    - group.domeswitch
    - group.oldswitch
    - group.dimmer
    #- group.furnace


furnace:
  name: Furnace 
  control: hidden
  entities:
    - switch.aeotec_zw078_heavy_duty_smart_switch_gen5_switch

domeswitch:
  name: Dome
  control: hidden
  entities:
    - switch.dome_on_off_plug_in_switch01_switch
    - switch.dome_on_off_plug_in_switch02_switch

zoozswitch:
  name: Zooz
  control: hidden
  entities:
    - switch.hank_hkzwso03_smart_plug_switch01

inovelliswitch:
  name: Inovelli
  control: hidden
  entities:
    - switch.inovelli_2ch_01_1
    - switch.inovelli_2ch_01_2

neoswitch:
  name: Neo_Coolcam
  control: hidden
  entities:
    # Modem Neo05 ID:33
    #- switch.neo_coolcam_power_plug_12a_switch05
    - script.restart_modem
    - switch.neo_coolcam_power_plug_12a_switch01
    - switch.neo_coolcam_power_plug_12a_switch02
    - switch.neo_coolcam_power_plug_12a_switch03
    - switch.neo_coolcam_power_plug_12a_switch04
    - switch.neo_coolcam_power_plug_12a_switch06
    - switch.neo_coolcam_power_plug_12a_switch07
    - switch.neo_coolcam_power_plug_12a_switch08


oldswitch:
  name: Intermatic
  control: hidden
  entities:
    -  switch.intermatic_ha02_appliance_module_switch 
    -  switch.intermatic_ha04c_outdoor_module_switch

dimmer:
  name: Room Light 
  control: hidden
  entities:
      ## Light SW ZEN21 (Node ID:24)
    - switch.zooz_zen21_switch_v20_switch_01
      ## Dimmer Zen22 MasterBedroom (Node ID:29)
    - light.zooz_zen22_dimmer_v2_1_level
      ## Dimmer Zen22 Vlad's Room (Node ID:32)
    - light.zooz_zen22_dimmer_v2_2_level
      ## Dimmer Zen22 Chat Room (Node ID:42)
    - light.zooz_zen22_dimmer_v2_3_level

###############################################################
#
#  NewTab "Automation" 
#
###############################################################
automation:
  view: yes
  name: AUTOMATION
  control: hidden
  entities:
    - group.all_automations


###############################################################
#
#  NewTab "MONITORING CHARTS" 
#
###############################################################
graphs:
  view: yes
  name: Monitor
  icon: mdi:chart-line-variant
  entities:
    - group.humidity
    - group.temperature
    - group.luminance
   #- group.mainfloorlux
    
temperature:
    name: Temperature
    entities:
    - history_graph.temperature_graphs
humidity:
    name: Humidity
    entities:
    - history_graph.humidity_graphs
luminance:
    name: Luminance
    entities:
    - history_graph.luminance_graphs
#mainfloorlux:
   #name: MainFloor
   #entities:
   #- history_graph.mainfloorlux_graphs
