- platform: hitron_coda
  #host: 192.168.0.1 
  #username: cusadmin
  #password: vladreamer
  host: !secret router_ip
  username: !secret router_username
  password: !secret router_password
  type: rogers 
  logger: debug
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False
