- platform: hitron_coda
  host: !secret router_ip
  username: !secret router_username
  password: !secret router_password
  type: rogers 
  logger: debug
  new_device_defaults:
    track_new_devices: True
    hide_if_away: False
