sensor.homeseer_hsm200_wireless_multisensor_luminance_1:
  ignored: false
  polling_intensity: 6000

############  
## SWITCHES
############  
switch.neo_coolcam_power_plug_12a_switch01:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.neo_coolcam_power_plug_12a_switch02:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.neo_coolcam_power_plug_12a_switch03:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.neo_coolcam_power_plug_12a_switch04:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.hank_hkzwso03_smart_plug_switch01:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.intermatic_ha02_appliance_module_switch:
  polling_intensity: 1
  refresh_value: true
  delay: 2
switch.intermatic_ha04c_outdoor_module_switch:
  polling_intensity: 1
  refresh_value: true
  delay: 2
